# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
install:
  - Rscript -e 'install.packages(c("dplyr","knitr","maps"), repos = "http://cran.rstudio.com")'
